/* eslint-disable @next/next/google-font-display */
/* eslint-disable @next/next/no-page-custom-font */
import "../styles/globals.css";
import { IExplorerItem } from "@tmnrp/react-explorer";
import { GoogleMaterialIcons } from "@tmnrp/react-google-material-icons";
import { AppProps } from "next/app";
import Head from "next/head";
import { NextRouter } from "next/router";
import { Layout } from "../components/Layout";
import { CONST_PAGES } from "../constants";
import { IBreadcrumbsMethods } from "@tmnrp/react-breadcrumbs";
import { useEffect, useRef } from "react";
import { useZSSetBreadcrumbRef } from "../utils/store";
import { useSyncBSToZS } from "../utils/browserStorage";

//
const _App = ({ Component, pageProps }: AppProps) => {
  //
  useSyncBSToZS();

  //
  const breadcrumbRef = useRef<IBreadcrumbsMethods>(null);
  const setBreadcrumbRef = useZSSetBreadcrumbRef();
  useEffect(() => setBreadcrumbRef(breadcrumbRef), [setBreadcrumbRef]);

  //
  return (
    <Layout>
      <Head>
        <title>TMNRP - Fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Component {...pageProps} />
    </Layout>
  );
};

//
export default _App;

//
export const getExplorerContent = (): Array<IExplorerItem> => [
  {
    icon: (
      <GoogleMaterialIcons className="pr-2" iconName="admin_panel_settings" />
    ),
    label: "Hateoas",
    props: { className: "flex space-x-2 mb-1" },
    items: [
      {
        icon: <GoogleMaterialIcons className="pr-2" iconName="people" />,
        label: "Role based actions",
        props: { className: "flex space-x-2 pl-4 mb-1 hover:text-primary" },
        url: CONST_PAGES.APP.HATEOAS.PATH,
      },
    ],
  },
  {
    icon: (
      <GoogleMaterialIcons className="pr-2" iconName="admin_panel_settings" />
    ),
    label: "Manage",
    props: { className: "flex space-x-2 mb-1" },
    items: [
      {
        icon: <GoogleMaterialIcons className="pr-2" iconName="people" />,
        label: "Roles",
        props: { className: "flex space-x-2 pl-4 mb-1 hover:text-primary" },
        url: CONST_PAGES.APP.SECURITY.ROLES.PATH,
      },
      {
        icon: <GoogleMaterialIcons className="pr-2" iconName="badge" />,
        label: "Users",
        props: { className: "flex space-x-2 pl-4 mb-1 hover:text-primary" },
        url: CONST_PAGES.APP.SECURITY.USERS.PATH,
      },
      {
        icon: <GoogleMaterialIcons className="pr-2" iconName="checklist_rtl" />,
        label: "Righs",
        props: { className: "flex space-x-2 pl-4 mb-1 hover:text-primary" },
        url: CONST_PAGES.APP.SECURITY.RIGHTS.PATH,
      },
    ],
  },
];
