###

POST http://localhost:3001/api/auth/login
content-type: application/json

{
  "username": "root",
  "password": "root"
}

###

GET http://localhost:3001/api/users
Authorization: bearer asdf
x-refresh-token: sample
